# Default values for k8s-pub-auth-varnish.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  certificateAwsArn: "" # The ARN of the aws certificate use by the ELB created for this service
  htpasswdSecret: "pub-varnish-auth" # The Kubernetes secret containing the contents of the .htpasswd file used for authentication.
replicaCount: 2

eksCluster: false

image:
  repository: coco/k8s-pub-auth-varnish
  pullPolicy: IfNotPresent
route53_elb_registrator:
  image: "coco/upp-route53-elb-dns-registrator:1.0.1"
